# deploy-production.yml
name: Deploy Production on Release Publish
on:
  release:
    types: [published]

jobs:
  Build-Deploy:
    runs-on: ubuntu-latest

    env:
      REGISTRY: ghcr.io
      ASPNETCORE_ENVIRONMENT: Production
      BACKEND_AZURE_APP: api-wahinekai-memberdatabase
      AZUREADCONNECTOR_AZURE_APP: azureadconnector-wahinekai-memberdatabase
      BACKEND_IMAGE: wahinekai/memberdatabase-backend
      AZUREADCONNECTOR_IMAGE: wahinekai/memberdatabase-azureadconnector

    steps:
      - name: Checkout Code
        uses: actions/checkout@v1

      - name: Set Release Version Environment Variable
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Setup up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PACKAGES_TOKEN }}

      - name: Build and Push Backend Docker Image
        uses: docker/build-push-action@v2
        with:
          push: true # Will only build if this is not here
          file: Dockerfile.backend
          tags: |
            ${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE }}:${{ env.RELEASE_VERSION }}
            ${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE }}:latest
          build-args: |
            ASPNETCORE_ENVIRONMENT=${{ env.ASPNETCORE_ENVIRONMENT }}

      - name: Build and Push Azure AD Connector Docker Image
        uses: docker/build-push-action@v2
        with:
          push: true # Will only build if this is not here
          file: Dockerfile.azureadconnector
          tags: |
            ${{ env.REGISTRY }}/${{ env.AZUREADCONNECTOR_IMAGE }}:${{ env.RELEASE_VERSION }}
            ${{ env.REGISTRY }}/${{ env.AZUREADCONNECTOR_IMAGE }}:latest
          build-args: |
            ASPNETCORE_ENVIRONMENT=${{ env.ASPNETCORE_ENVIRONMENT }}

      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.PRODUCTION_AZURE_CREDENTIALS }}

      - name: Deploy Backend to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.BACKEND_AZURE_APP }}
          images: ${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE }}:latest

      - name: Deploy Azure AD Connector to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZUREADCONNECTOR_AZURE_APP }}
          images: ${{ env.REGISTRY }}/${{ env.AZUREADCONNECTOR_IMAGE }}:latest

      - name: Azure logout
        run: |
          az logout
