# deploy-staging.yml
name: Deploy Staging on Push to Main and Consolidate Repos
on:
  push:
    branches:
      - main
      - users/cbpodd/consolidateRepos

jobs:
  Build-Deploy:
    runs-on: ubuntu-latest

    env:
      REGISTRY: ghcr.io
      ASPNETCORE_ENV: Staging
      BACKEND_AZURE_APP: dev-api-wahinekai-memberdatabase
      AZUREADCONNECTOR_AZURE_APP: dev-azureadconnector-wahinekai-memberdatabase
      BACKEND_IMAGE: wahinekai/memberdatabase-backend
      AZUREADCONNECTOR_IMAGE: wahinekai/memberdatabase-azureadconnector
      TAG: dev

    steps:
      - name: Checkout Code
        uses: actions/checkout@v1

      - name: Setup up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PACKAGES_TOKEN }}

      - name: Build and Push Backend Docker Image
        uses: docker/build-push-action@v2
        with:
          push: true # Will only build if this is not here
          file: Dockerfile.backend
          tags: |
            ${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE }}:${{ env.TAG }}
          build-args: |
            ASPNETCORE_ENV=${{ env.ASPNETCORE_ENV }}

      - name: Build and Push Azure AD Connector Docker Image
        uses: docker/build-push-action@v2
        with:
          push: true # Will only build if this is not here
          file: Dockerfile.azureadconnector
          tags: |
            ${{ env.REGISTRY }}/${{ env.AZUREADCONNECTOR_IMAGE }}:${{ env.TAG }}
          build-args: |
            ASPNETCORE_ENV=${{ env.ASPNETCORE_ENV }}

      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.DEVELOPMENT_AZURE_CREDENTIALS }}

      - name: Deploy Backend to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.BACKEND_AZURE_APP }}
          images: ${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE }}:${{ env.TAG }}

      - name: Deploy Azure AD Connector to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZUREADCONNECTOR_AZURE_APP }}
          images: ${{ env.REGISTRY }}/${{ env.AZUREADCONNECTOR_IMAGE }}:${{ env.TAG }}

      - name: Azure logout
        run: |
          az logout
