# deploy-staging.yml
name: Deploy Staging on Push to Main
on:
  push:
    branches:
      - main

jobs:
  Build-Deploy:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      ASPNETCORE_ENV: Staging
      AZURE_APP: backend-development-wahinekaimemberdatabase
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1

      - name: Setup up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PACKAGES_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          push: true # Will only build if this is not here
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository }}:latest
          build-args: |
            ASPNETCORE_ENV=${{ env.ASPNETCORE_ENV }}
            PACKAGES_TOKEN=${{ secrets.PACKAGES_TOKEN }}

      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.DEVELOPMENT_AZURE_CREDENTIALS }}

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_APP }}
          images: ${{ env.REGISTRY }}/${{ github.repository }}:latest

      - name: Azure logout
        run: |
          az logout
